 function [Acc_Prec_FprMaxRIG] = OptFeature_RIG(M,K,X,Y,Targets)  
 tic  
 %%Optimal features generated by IG
%%%ROBUST INFORMATIN GAIN,,

List1_Feature=indexing_Feature(M,K); 
  
%%%%%%%===================================%
   [IGvect]= InformationGain(X,Y);%
   [IG1,indexes] = sort(IGvect,'ascend');
   n=length(IG1);
   Nbr_bins=round(sqrt(n)) ;%
   range=max(IG1)-min(IG1);
   BinWidth=range/Nbr_bins;
   fprintf('The computed IG values from this sample size falls in range[ %3.4f - %3.4f]\n',min(IG1),max(IG1))
      if range==0
       fprintf('The IG  for your data is the same\n')
   else
 AccRIG=zeros(3,Nbr_bins);%%Preallocating 3 parameters ,fpr, acc, prec,,,,
 CUM=zeros(1,Nbr_bins);
       for i=1:Nbr_bins
           CumEdge=min(IG1)+(i-1)*BinWidth ;
           CUM(i)=CumEdge;
           RemainVect=find(IG1>=CumEdge);
           idxInp=indexes(RemainVect);%
           InputIG=X(:,idxInp);%%The inputs at i  loop
           Ac_Pre_FprRIG=NNW_Alg3Metr(InputIG',Targets);%
            AccRIG(:,i)=Ac_Pre_FprRIG;
           Acc1=AccRIG(1,:);
            [AccMax,Idxmax]=max(Acc1);
           Precion=AccRIG(2,:);
           PrecMax=Precion(Idxmax);
           FPRate=AccRIG(3,:);
           FprMax=FPRate(Idxmax);
           idxoptimal=indexes(IG1>=CUM(Idxmax));    Optimal_Features=List1_Feature(idxoptimal);
          Acc_Prec_FprMaxRIG=[AccMax PrecMax FprMax];
       end
           
  L=length(Optimal_Features);
  fprintf('The number of bins is [%d]\n',Nbr_bins);
  fprintf('The number of selected Optimal features is [%d] in [%3.2f]seconds\n',L);
 fprintf('The optimal index  for cumulative edges [%d]\n',Idxmax);
 fprintf('The computed performance at consecutive new cutoff point is shown below \n')
  fprintf('-----------------------------------\n')
 fprintf('Sn0 |Accuracy |Precison |FPR rate|\n')
 fprintf('-----------------------------------\n')
 for j=1:Nbr_bins
 fprintf('%2d |%3.2f    |%3.2f    |%3.3f     | \n',j,Acc1(j),Precion(j), FPRate(j))
 end
  fprintf('-----------------------------------\n')
 fprintf('The optimal performance for this input is [%3.2f%%]of Accuracy,[%3.2f%%]of precision, and [%3.3f] of FPR rate \n',AccMax, PrecMax, FprMax); 
 
 end  
    
 toc  
  fprintf('The  elapse time for RIG is [%3.3f]\n',toc);
    end
           
           
           
           
           
           
           
           
   