 function [AccT_I_G ] = Traditional_IG(X,Y,Targets)  
 %%Optimal features generated by IG , whereby you decide your top number of
 %%ranked features 

   [IGvect]= InformationGain(X,Y);      
   [IG1,indexes] = sort(IGvect,'descend');
   n=length(IG1);
%set your proposed percentage or use List of your parcentages P=[50,60,70}

    Nbr_Feat=round(n*0.5);%%We need number of 50 or 60 features 

    idxInpFS=indexes(:,1:Nbr_Feat);
   Ranked_FS=idxInpFS';
           InputTIG=X(:,idxInpFS);
   AccT_I_G =NNW_Alg3Metr(InputTIG',Targets);
    fprintf('-------------------------------\n')
    fprintf('Performance for TIG\n')
    fprintf('-------------------------------\n')
    fprintf('|Accuracy | Precision| FPRrate|\n')
   fprintf(' |%3.2f    |  %3.2f    |%3.3f  |\n', AccT_I_G(1), AccT_I_G(2), AccT_I_G(3))
      fprintf('-------------------------------\n')
  fprintf('The Ranked  selected  features, and its IG  by using TIG is \n')
      fprintf('Sn0   |  Top Features\n')
      fprintf('-------------------------------\n')
   for j=1:length( Ranked_FS)
      fprintf('|%d   | %d|\n',j,Ranked_FS(j))
    end
  fprintf('---------------------------------------\n')
     end
